import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Search from "../icons/Search";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google clone </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <form>
        <div className="w-full flex justify-center">
          <Image alt="logo" width={300} height={100} src="/google.jpeg" />
          <Search />
        </div>
      </form>
    </div>
  );
}
